# Generated by Django 3.2.8 on 2021-11-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, verbose_name='Никнейм')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('rating', models.IntegerField(blank=True, default=1200, verbose_name='Рейтинг')),
                ('history', models.TextField(blank=True, null=True, verbose_name='История сыгранных партий')),
            ],
        ),
    ]
