# Generated by Django 3.2.8 on 2021-11-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notation', models.CharField(max_length=80, verbose_name='Нотация Форсайда-Эдвартса (FEN)')),
                ('status', models.IntegerField(default=2, verbose_name='Текущее состояние игры')),
                ('time_last_move', models.DateTimeField(auto_now=True, verbose_name='Время последнего хода')),
                ('time_start', models.DateTimeField(auto_now_add=True, verbose_name='Время начала партии')),
                ('time_end', models.DateTimeField(null=True, verbose_name='Время окончания партии')),
            ],
        ),
    ]
