# Generated by Django 3.2.8 on 2021-11-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notation', models.CharField(max_length=80, verbose_name='Нотация Форсайда-Эдвартса (FEN)')),
                ('status', models.IntegerField(default=2, verbose_name='Текущее состояние игры')),
                ('time_last_move', models.DateTimeField(auto_now=True, verbose_name='Время последнего хода')),
                ('time_start', models.DateTimeField(auto_now_add=True, verbose_name='Время начала партии')),
                ('time_end', models.DateTimeField(null=True, verbose_name='Время окончания партии')),
                ('player1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1', to='players.player', verbose_name='Белые')),
                ('player2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2', to='players.player', verbose_name='Чёрные')),
            ],
        ),
    ]
